### PR TITLE
Rename Last Call Working Draft

### PR DESCRIPTION
**Pull request by xfq**

### CODE REVIEW

**Comment by dontcallmedom** [comment]
could you instead of completely removing the "last call" column, replacing it with a "wide review start" column? I think it's useful for the group to keep the need of scheduling its wide reviews visible.

**Comment by xfq** [comment]
Done.

**Comment by xfq** [comment]
@dontcallmedom Do we need to move some specs to the "wide review start" column, e.g., some of the concrete sensor specs?

**Comment by xfq** [comment]
Fixed in #6 now.

**Pull request merged**
